# Generated by Django 3.1.4 on 2021-01-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("price", models.FloatField()),
                (
                    "sku",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
